/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "index.html",
    "about.html",
    "service.html",
    "contact.html",
    "./*.{html,js,php}",
    "./src/js/*.js",
  ],
  theme: {
    extend: {
      backgroundImage: {
        'cover-hero': "url('../../src/image/cover-hero.png')",
        'about-cover-hero': "url('../../src/image/about-cover.png')",
      },
      colors:{
        brandContactBorder: "#CECECE",
        brandFooter: "#16203A",
        brandcard1: "#C5B9FA",
        brandcard2: "#EF8B7C",
        brandcard3: "#749AF0",
        brandFormBody: "#F1EEE1",
        brandFormBorder: "#DCDCDC",
        brandGreenBadge: "#38B000",
        brandValue: "#F4EFE1",
        brandValue2: "#006837",
        brandTestimony: "#012C1F",
        brandBgColor: "#FEFBED",
        brandBrown: "#201721",
        brandBlack: "#201F1A",
        brandBlack1x: "#161616",
        brandBlue: "#1C9AEA",
        brandBlueDeep: "#01102E",
        brandBlueStart: "#2AC1F2",
        brandBlueEnd: "#0153DB",
        brandBlue1x: "#0F77E3",
        brandBlue2x: "#0163C9",
        brandBlue3x: "#0A6BE0",
        brandBlue4x: "#1382E5",
        brandLightBlue1x: "#B5DCFF",
        brandGray: "#9E9E9E",
        brandGray2x: "#F0F0F0",
        brandGray3x: "#E8E8E8",
        brandGray4x: "#8F9DB7",
        brandGray5x: "#F6F6F6",
        brandGray6x: "#F9FBFA",
        brandGray7x: "#CCCCCC",
        brandGray8x: "#AFAFAF",
        brandGray9x: "#A1A1A1",
        brandGray10x: "#F3F3F3",
        brandGreenLite: "#F2F7F6",
        brandGreen: "#3BB75E",
        brandGreen1x: "#A9DECC",
        brandPurple: "#E5C2FA",
        brandPurple1x: "#917B94",
        brandYellow: "#F2C94C",
        brandYellow1x: "#FEE4B3",
        brandYellowLite: "#FFF7E8",
        brandDarkViolet1x: "#2A2AB2",
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
        'position': 'position',
      },
      borderRadius:{
        five: "0.3125rem",
        ten: "0.625rem",
        twenty: "1.25rem",
        thirty: "1.875rem",
        forty: "2.5rem",
        fifty: "3.125rem",
        eighty: "5rem",
        hundred: "6.25rem",
        fiftyPercent: "50%",
      },
      content:{
        "logo": "url['./assets/image/logo.png']",
      },
      screens:{
        'mds': {'min': '500px', 'max': '639px'},
        'bxs': {'min': '300px', 'max': '350px'},
        'xs': {'min': '200px', 'max': '300px'},
        'xsHeight': { 'raw': '(max-height:510px)' },
      },
      spacing:{
        '18': '4.5rem',
        navIcon: '20px',
        authWrapper: '34%',
      },
      fontSize: {
        sm: ['14px', '20px'],
        thirteen: ['13px', '18px'],
        fifteen: ['15px', '20px'],
      },
      fontFamily:{
        avenirBlack: ["avenir-black", "sans-serif"],
        avenirBook: ["avenir-book", "sans-serif"],
        avenirHeavy: ["avenir-heavy", "sans-serif"],
        avenirLight: ["avenir-light", "sans-serif"],
        avenirMedium: ["avenir-medium", "sans-serif"],
        avenirRegular: ["avenir-regular", "sans-serif"],
        avenirRoman: ["avenir-roman", "sans-serif"],
        avenirBlack: ["avenir-black", "sans-serif"],
        unboundedBlond: ["unbounded-blond", "sans-serif"],
        unboundedBold: ["unbounded-bold", "sans-serif"],
        unboundedBlack: ["unbounded-black", "sans-serif"],
        unboundedLight: ["unbounded-light", "sans-serif"],
        unboundedMedium: ["unbounded-medium", "sans-serif"],
        unboundedRegular: ["unbounded-regular", "sans-serif"],
      },
      zIndex: {
        '70': '70',
        '80': '80',
        '100': '100',
      },
      borderWidth:{
        '0.3': '0.01875rem',
        '0.5': '0.03125rem',
      },
      outlineWidth:{
        '0.3': '0.01875rem',
        '0.5': '0.03125rem',
      },
      minWidth: {
        '1/2': '50%',
        '350': '21.875rem',
      },
      spacing:{
        '3px': '0.1875rem',
        'sixPixel': "0.375rem",
        '18': '4.5rem',
        'top18.5': '74px',
        '18px': '1.125rem',
        '40px': '2.5rem',
        '45px': '2.8125rem',
        '60px': '3.75rem',
        '88': '5.5rem',
        '100': '6.25rem',
        '130px': '8.125rem',
        '202': '12.625rem',
        '254': '15.875rem',
        '280': '17.5rem',
        '307': '19.1875rem',
        '322': '20.125rem',
        '350': '21.875rem',
        '380': '23.75rem',
        '400': '25rem',
        '410': '25.625rem',
        '420': '26.25rem',
        '550': '34.375rem',
        '618': '38.625rem',
        '700': '43.75rem',
        '70px': '4.375rem',
        navIcon: '20px',
        authWrapper: '34%',
        dashScrollableHeight: 'calc(100% - 10px)',
        icon: '20px',
        onePixel: '0.0625rem',
        threePixel: '0.150rem',
        tenPixel: '0.625rem',
        fivePercent: '5%',
        tenPercent: '10%',
        twelvePercent: '12%',
        thirteenPercent: '13%',
        fourteenPercent: '14%',
        fifteenPercent: '15%',
        seventeenPercent: '17%',
        eighteenPercent: '18%',
        nineteenPercent: '19%',
        twentyPercent: '20%',
        twentyTwoPercent: '22%',
        twentyFourPercent: '24%',
        twentyFivePercent: '25%',
        thirtyPercent: '30%',
        thirtyTwoPercent: '32%',
        thirtyFivePercent: '35%',
        thirtySixPercent: '36%',
        thirtyEightPercent: '38%',
        fortyPercent: '40%',
        fortyFivePercent: '45%',
        fortySevenPercent: '47%',
        fortyEightPercent: '48%',
        fiftyPercent: '50%',
        fiftyTwoPercent: '52%',
        fiftyFivePercent: '55%',
        sixtyPercent: '60%',
        sixtyTwoPercent: '62%',
        sixtyFivePercent: '65%',
        sixtySixPercent: '66%',
        sixtySevenPercent: '67%',
        seventyPercent: '70%',
        seventyFivePercent: '75%',
        seventyEightPercent: '78%',
        eightyPercent: '80%',
        eightyOnePercent: '81%',
        eightyThreePercent: '83%',
        eightyFourPercent: '84%',
        eightyFivePercent: '85%',
        eightyEightPercent: '88%',
        ninetyPercent: '90%',
        ninetyFivePercent: '95%',
        hundredPercent: '100%',
        oneTwentyPercent: '120%',
        oneFiftyPercent: '150%',
        twoHundredPercent: '200%',
      },
    },
  },
  plugins: [],
}
